---
title: "CapstoneExerciseFeb28"
author: "Markus Jury"
date: "February 28, 2018"
output: 
  html_document:
    theme: flatly
    toc: yes
    highlight: haddock
    df_print: tibble

---

## Loading Initial Libraries
```{r,results='hide'}
library("tidyverse")
library("rio")

```


## Importing Data

```{r}
maindata <- import("./20160213_data/main_data.csv", header=FALSE)
```

## Recoding Missing Values

```{r}
maindata <- maindata %>% map(tolower)
```

```{r}
maindata <- map(maindata,na_if,"\\n")
```

```{r}
maindata <- map(maindata,na_if,"null")
```

```{r}
maindata <- map(maindata,na_if,"-1") %>% as.tibble
```

```{r}
datanames <- import("datanames.csv")
```

## Renaming Column Names

```{r}
datanames <- as.matrix(datanames)
```

```{r}
colnames(maindata) <- datanames
```

## Reclassifying Columns

```{r}
for (i in c(3:6,10:14,19:21,39:46,49)){
  maindata[[i]] <- as.numeric(maindata[[i]])
}
for (i in c(1,7:9,15:17,23:33,36:38,47)){
  maindata[[i]] <- as.factor(maindata[[i]])
}
```

## Releveling Refgroups

```{r}
maindata$guest_race <- maindata$guest_race %>% relevel(ref="white")
maindata$guest_gender <- maindata$guest_gender %>% relevel(ref="male")
```

## Creating namebycity

```{r}
maindata <- maindata %>% mutate(namebycity = paste(guest_first_name,city))
maindata
```

## Import + Merge Survey Results

```{r}
surveyresults <- import("./20160213_data/name_survey_results.xlsx")
```

```{r}
surveyresults$guest_first_name <- tolower(surveyresults$guest_first_name)
```

```{r}
maindata <- left_join(maindata, surveyresults, by="guest_first_name")
```

## Changing Survey Variable

```{r}
maindata$guest_race_continuous <- (maindata$guest_race_continuous) - 1
```

## Creating Indicator Variables

```{r}
maindata <- maindata %>% mutate(host_race_black = ifelse(host_race=="black",1,0))
```

```{r}
maindata <- maindata %>% mutate(host_race_white = ifelse(host_race=="white",1,0))
```

```{r}
maindata <- maindata %>% mutate(host_male = ifelse(host_gender=="male",1,0))
```
 
## Categorical Host Age Variable

```{r}
maindata <- maindata %>% mutate(host_age_cat = case_when(
  host_age %in% c("young","young/uu","uu/young","young/na","na/young") ~ "0",
  host_age %in% c("middle/young","young/middle") ~ "1",
  host_age %in% c("middle","middle/uu","uu/middle","middle/na",
                 "na/middle") ~ "2",
  host_age %in% c("middle/old","old/middle") ~ "3",
  host_age %in% c("old/middle","old","old/uu","uu/old","old/na","na/old") ~ "4"
))
```

## Binary variables for Host Characteristics

```{r}
maindata <- maindata %>% 
  mutate(ten_reviews=ifelse(number_of_reviews>=10,1,0),
        five_star_property=ifelse(apt_rating==5,1,0),
        multiple_listings=ifelse(number_of_listings>1,1,0),
        shared_property=ifelse(property_setup %in% c("private room",
                                                     "shared room"),1,0),
        shared_bathroom=ifelse(bathrooms<1.5 & shared_property==1,1,0),
        has_cleaning_fee=ifelse(!is.na(cleaning_fee),1,0),
        strict_cancellation=ifelse(cancellation_policy=="strict",1,0),
        young=ifelse(host_age_cat==0,1,0),
        middle=ifelse(host_age_cat %in% c(1,2),1,0),
        old=ifelse(host_age_cat %in% c(3,4),1,0)
  )
```
                            
                                




